// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL77r-IsaHA6EzEbkVgSV-UO25Ro3Ymls',
    appId: '1:123618775176:web:8313a06629e1be17620f3d',
    messagingSenderId: '123618775176',
    projectId: 'tkpm-uts-app',
    authDomain: 'tkpm-uts-app.firebaseapp.com',
    storageBucket: 'tkpm-uts-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KYE20VYT1VtF29SembywsLNH1pK69gY',
    appId: '1:123618775176:android:65622c52a6602f43620f3d',
    messagingSenderId: '123618775176',
    projectId: 'tkpm-uts-app',
    storageBucket: 'tkpm-uts-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLABDUBTCjcT3wqMJJ9opd3GWRAfSsaEU',
    appId: '1:123618775176:ios:b15526262ef3a602620f3d',
    messagingSenderId: '123618775176',
    projectId: 'tkpm-uts-app',
    storageBucket: 'tkpm-uts-app.firebasestorage.app',
    iosBundleId: 'com.example.utsApp',
  );

}